const data = {
  'tags': [{
    'id': 1,
    'name': '书画',
    'state': 'LIVE',
    'type': 'Frist',
    'squen': 1,
    'secondTags': [{
      'id': 67,
      'name': '000001',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 1,
      'secondTags': null,
      'labels': []
    }, {
      'id': 58,
      'name': '1212',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 2,
      'secondTags': null,
      'labels': [{
        'id': 7,
        'name': '钢琴一级',
        'description': '钢琴考级 一级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132014177455_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 11,
        'name': '钢琴五级',
        'description': '钢琴考级 五级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132015044763_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 12,
        'name': '钢琴六级',
        'description': '钢琴考级 六级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132015188046_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 234,
        'name': '考级测试01',
        'description': '考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01考级测试01',
        'url': 'http://7xszyu.com1.z0.glb.clouddn.com/1510039835951_wh200x200.jpg',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }]
    }, {
      'id': 22,
      'name': '素描',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 8,
      'secondTags': null,
      'labels': [{
        'id': 2,
        'name': '古典钢琴',
        'description': '古典钢琴',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132010172462_wh132x132.png',
        'type': 'NeiRong',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 11,
        'name': '钢琴五级',
        'description': '钢琴考级 五级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132015044763_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }]
    }, {
      'id': 8,
      'name': '水粉',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 9,
      'secondTags': null,
      'labels': []
    }, {
      'id': 7,
      'name': '水彩',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 19,
      'secondTags': null,
      'labels': []
    }, {
      'id': 10,
      'name': '油画',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 20,
      'secondTags': null,
      'labels': []
    }, {
      'id': 9,
      'name': '国画',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 21,
      'secondTags': null,
      'labels': []
    }, {
      'id': 19,
      'name': '儿童画',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 52,
      'secondTags': null,
      'labels': []
    }, {
      'id': 52,
      'name': '漫画',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 54,
      'secondTags': null,
      'labels': []
    }, {
      'id': 60,
      'name': '话题测试呀7.17',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 58,
      'secondTags': null,
      'labels': []
    }, {
      'id': 5,
      'name': '硬笔书法',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 60,
      'secondTags': null,
      'labels': []
    }, {
      'id': 6,
      'name': '软笔书法',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 95,
      'secondTags': null,
      'labels': []
    }, {
      'id': 27,
      'name': '其他书画',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 96,
      'secondTags': null,
      'labels': []
    }, {'id': 54, 'name': '美术考级', 'state': 'LIVE', 'type': 'Second', 'squen': 97, 'secondTags': null, 'labels': []}],
    'labels': []
  }, {
    'id': 3,
    'name': '器乐',
    'state': 'LIVE',
    'type': 'Frist',
    'squen': 5,
    'secondTags': [{
      'id': 16,
      'name': '钢琴',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 15,
      'secondTags': null,
      'labels': [{
        'id': 2,
        'name': '古典钢琴',
        'description': '古典钢琴',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132010172462_wh132x132.png',
        'type': 'NeiRong',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 6,
        'name': '钢琴大神',
        'description': '钢琴大神的殿堂',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132014049812_wh132x132.png',
        'type': 'NeiRong',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 10,
        'name': '钢琴四级',
        'description': '钢琴考级 四级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132014556293_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 14,
        'name': '钢琴八级',
        'description': '钢琴考级 八级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132016388368_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 15,
        'name': '钢琴九级',
        'description': '钢琴考级 九级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132017011888_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 11,
        'name': '钢琴五级',
        'description': '钢琴考级 五级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132015044763_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 7,
        'name': '钢琴一级',
        'description': '钢琴考级 一级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132014177455_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 4,
        'name': '钢琴练习',
        'description': '钢琴练习曲都在这儿',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132013317266_wh132x132.png',
        'type': 'NeiRong',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 8,
        'name': '钢琴二级',
        'description': '钢琴考级 二级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132014317940_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 12,
        'name': '钢琴六级',
        'description': '钢琴考级 六级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132015188046_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 16,
        'name': '钢琴十级',
        'description': '钢琴考级 十级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132017185958_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 13,
        'name': '钢琴七级',
        'description': '钢琴考级 七级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132015377194_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 9,
        'name': '钢琴三级',
        'description': '钢琴考级 三级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132014438707_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 5,
        'name': '钢琴小白',
        'description': '我是一个钢琴小白',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132013502704_wh132x132.png',
        'type': 'NeiRong',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }]
    }, {
      'id': 15,
      'name': '吉他',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 16,
      'secondTags': null,
      'labels': [{
        'id': 2,
        'name': '古典钢琴',
        'description': '古典钢琴',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132010172462_wh132x132.png',
        'type': 'NeiRong',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }, {
        'id': 231,
        'name': '软笔十级',
        'description': '软笔考级十级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_21_201610221323009614_wh200x200.jpg',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }]
    }, {
      'id': 28,
      'name': '古筝',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 17,
      'secondTags': null,
      'labels': []
    }, {
      'id': 18,
      'name': '小提琴',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 18,
      'secondTags': null,
      'labels': []
    }, {
      'id': 17,
      'name': '管乐',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 28,
      'secondTags': null,
      'labels': [{
        'id': 227,
        'name': '软笔六级',
        'description': '软笔考级六级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_21_201610221320344311_wh200x200.jpg',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }]
    }, {
      'id': 29,
      'name': '弦乐',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 29,
      'secondTags': null,
      'labels': [{
        'id': 231,
        'name': '软笔十级',
        'description': '软笔考级十级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_21_201610221323009614_wh200x200.jpg',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }]
    }, {
      'id': 33,
      'name': '其他器乐',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 33,
      'secondTags': null,
      'labels': []
    }, {
      'id': 32,
      'name': '打击乐',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 33,
      'secondTags': null,
      'labels': []
    }, {'id': 57, 'name': '01010', 'state': 'LIVE', 'type': 'Second', 'squen': 57, 'secondTags': null, 'labels': []}],
    'labels': []
  }, {
    'id': 2,
    'name': '舞蹈',
    'state': 'LIVE',
    'type': 'Frist',
    'squen': 10,
    'secondTags': [{
      'id': 14,
      'name': '街舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 11,
      'secondTags': null,
      'labels': []
    }, {
      'id': 13,
      'name': '国标舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 12,
      'secondTags': null,
      'labels': []
    }, {
      'id': 12,
      'name': '芭蕾舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 13,
      'secondTags': null,
      'labels': [{
        'id': 39,
        'name': '吉他三级',
        'description': '吉他考级 三级',
        'url': 'http://7xpx8n.com1.z0.glb.clouddn.com/pic_album_ad_10_201609132023257381_wh132x132.png',
        'type': 'KaoJi',
        'ifMyFollowd': 0,
        'totalElements': null,
        'appShareUrl': null
      }]
    }, {
      'id': 35,
      'name': '现代舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 14,
      'secondTags': null,
      'labels': []
    }, {
      'id': 11,
      'name': '古典舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 24,
      'secondTags': null,
      'labels': []
    }, {
      'id': 24,
      'name': '民族舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 25,
      'secondTags': null,
      'labels': []
    }, {
      'id': 25,
      'name': '肚皮舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 26,
      'secondTags': null,
      'labels': []
    }, {
      'id': 36,
      'name': '集体舞',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 35,
      'secondTags': null,
      'labels': []
    }, {'id': 26, 'name': '其他舞蹈', 'state': 'LIVE', 'type': 'Second', 'squen': 36, 'secondTags': null, 'labels': []}],
    'labels': []
  }, {
    'id': 37,
    'name': '表演',
    'state': 'LIVE',
    'type': 'Frist',
    'squen': 37,
    'secondTags': [{
      'id': 44,
      'name': '舞台表演',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 38,
      'secondTags': null,
      'labels': []
    }, {
      'id': 43,
      'name': '朗诵主持',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 39,
      'secondTags': null,
      'labels': []
    }, {
      'id': 38,
      'name': '流行声乐',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 40,
      'secondTags': null,
      'labels': []
    }, {
      'id': 39,
      'name': '美声声乐',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 42,
      'secondTags': null,
      'labels': []
    }, {
      'id': 40,
      'name': '民族声乐',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 43,
      'secondTags': null,
      'labels': []
    }, {
      'id': 42,
      'name': '戏剧',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 44,
      'secondTags': null,
      'labels': []
    }, {
      'id': 45,
      'name': '模特',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 45,
      'secondTags': null,
      'labels': []
    }, {
      'id': 47,
      'name': '武术',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 47,
      'secondTags': null,
      'labels': []
    }, {
      'id': 48,
      'name': '其他表演',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 48,
      'secondTags': null,
      'labels': []
    }, {'id': 55, 'name': '朗诵考级', 'state': 'LIVE', 'type': 'Second', 'squen': 55, 'secondTags': null, 'labels': []}],
    'labels': []
  }, {
    'id': 49,
    'name': '操场',
    'state': 'LIVE',
    'type': 'Frist',
    'squen': 49,
    'secondTags': [{
      'id': 65,
      'name': '哎呀呀呀呀',
      'state': 'LIVE',
      'type': 'Second',
      'squen': 1,
      'secondTags': null,
      'labels': []
    }, {'id': 50, 'name': '闲聊', 'state': 'LIVE', 'type': 'Second', 'squen': 50, 'secondTags': null, 'labels': []}],
    'labels': []
  }]
}
export default data